version: 2

general:
  branches:
    - master

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run: ./gradlew clean
      - run: ./gradlew setupDecompWorkspace
      - run: ./gradlew build

      - store_artifacts:
          path: build/libs/
